using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Plang.Compiler.Backend.ASTExt;
using Plang.Compiler.TypeChecker;
using Plang.Compiler.TypeChecker.AST;
using Plang.Compiler.TypeChecker.AST.Declarations;
using Plang.Compiler.TypeChecker.AST.Expressions;
using Plang.Compiler.TypeChecker.AST.States;
using Plang.Compiler.TypeChecker.AST.Statements;

namespace Plang.Compiler.Backend.Elixir
{
    /// <summary>
    /// Runtime code-generation backend that emits an executable Elixir (BEAM) mix project
    /// from a verified P program. Peer of the PChecker (C#) and PEx (Java) backends; concerned
    /// only with <em>running</em> a P design, not verifying it.
    ///
    /// M1 (walking skeleton): each P machine becomes a <c>:gen_statem</c> module; the generated
    /// <c>&lt;Prefix&gt;.Supervisor</c> starts the (non-spec) machines. Payloads, the type system,
    /// cross-machine sends, defer/ignore, and specs arrive in later milestones.
    ///
    /// Like PObserve, this backend has no compilation stage: the generated mix project is meant
    /// to be consumed as a dependency by a host application, which builds it with the standard
    /// Elixir toolchain (<c>mix</c>). <see cref="ICodeGenerator.HasCompilationStage"/> stays false.
    ///
    /// Logging is a runtime concern: like <c>PCheckerCodeGenerator</c>, the emitted code contains
    /// no logging statements of its own — it calls <c>PRuntime</c> helpers (from the vendored
    /// <c>p_runtime</c> library) which record the trace as a side effect.
    /// </summary>
    public class ElixirCodeGenerator : ICodeGenerator
    {
        public IEnumerable<CompiledFile> GenerateCode(ICompilerConfiguration job, Scope globalScope)
        {
            var modulePrefix = ModulePrefix(job);
            var appName = SnakeCase(modulePrefix);

            // Non-spec machines are the executable state machines; specs become passive monitors
            // in a later milestone (M5) and are skipped here.
            var machines = globalScope.Machines.Where(m => !m.IsSpec).ToList();

            // WriteFile (DefaultCompilerOutput) does not create intermediate directories, and the
            // generated files live under lib/<app>/. Create that directory now, before the
            // orchestrator writes the returned files. PObserve follows the same "touch the output
            // dir during GenerateCode" pattern for its pom.xml.
            Directory.CreateDirectory(Path.Combine(job.OutputDirectory.FullName, "lib", appName));

            var files = new List<CompiledFile>
            {
                GenerateMixExs(modulePrefix, appName),
                GenerateSupervisor(modulePrefix, appName, machines)
            };

            files.AddRange(machines.Select(m => GenerateMachine(modulePrefix, appName, m)));
            return files;
        }

        private static CompiledFile GenerateMixExs(string modulePrefix, string appName)
        {
            var file = new CompiledFile("mix.exs");
            file.Stream.Write(
$@"defmodule {modulePrefix}.MixProject do
  use Mix.Project

  def project do
    [
      app: :{appName},
      version: ""0.1.0"",
      elixir: ""~> 1.17"",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # No `mod:` application callback by default: starting machines on Application.start is
  # surprising. The host adds {modulePrefix}.Supervisor to its own supervision tree explicitly.
  def application do
    [extra_applications: [:logger]]
  end

  defp deps do
    [
      {{:p_runtime, github: ""ausimian/p_runtime""}}
    ]
  end
end
");
            return file;
        }

        private static CompiledFile GenerateSupervisor(string modulePrefix, string appName, IReadOnlyCollection<Machine> machines)
        {
            var children = string.Join(",\n",
                machines.Select(m => $"      {{{modulePrefix}.{m.Name}, nil}}"));
            if (children.Length > 0)
            {
                children = "\n" + children + "\n    ";
            }

            var file = new CompiledFile(Path.Combine("lib", appName, "supervisor.ex"));
            file.Stream.Write(
$@"defmodule {modulePrefix}.Supervisor do
  @moduledoc """"""
  Entry point for the generated P program. The host adds this module to its own
  supervision tree; it starts the program's state machines.

  Generated by the P compiler's Elixir backend.
  """"""
  use Supervisor

  def start_link(init_arg \\ []) do
    Supervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
    children = [{children}]
    Supervisor.init(children, strategy: :one_for_one)
  end
end
");
            return file;
        }

        /// <summary>
        /// Emits one <c>:gen_statem</c> module per P machine, in
        /// <c>[:handle_event_function, :state_enter]</c> mode. State-functions mode is avoided
        /// deliberately: it would require a function named after each state, and P state names are
        /// PascalCase (e.g. <c>Init</c>), which is not a valid Elixir function name. A single
        /// <c>handle_event/4</c> matching on the state atom sidesteps that entirely.
        ///
        /// P's <c>entry</c> runs as a synthetic <c>:__entry__</c> internal event queued on arrival
        /// (from <c>init</c> and from every <c>goto</c>), so entry executes in the new state.
        /// </summary>
        private static CompiledFile GenerateMachine(string modulePrefix, string appName, Machine machine)
        {
            var sb = new StringBuilder();
            sb.Append(
$@"defmodule {modulePrefix}.{machine.Name} do
  @moduledoc """"""
  Generated from P machine `{machine.Name}` by the P compiler's Elixir backend. Do not edit.

  Encoded as a :gen_statem in handle_event_function + state_enter mode. P `entry` runs as a
  synthetic `:__entry__` internal event queued on arrival, so entry executes in the new state
  across every transition.
  """"""
  @behaviour :gen_statem

  @p_machine ""{machine.Name}""

  defstruct []

  # :transient — a P machine that halts (stops :normal) is not restarted; only an abnormal
  # crash would restart it. P machines halt or live forever (see DESIGN.md, Open Question 3).
  @doc false
  def child_spec(arg) do
    %{{id: __MODULE__, start: {{__MODULE__, :start_link, [arg]}}, restart: :transient}}
  end

  def start_link(args \\ nil) do
    :gen_statem.start_link(via(), __MODULE__, args, [])
  end

  # Registered by P name so the program (and tests) can address the machine without its pid.
  defp via, do: {{:via, Registry, {{PRuntime.Registry, @p_machine}}}}

  @impl true
  def callback_mode, do: [:handle_event_function, :state_enter]

  @impl true
  def init(_args) do
    PRuntime.created(@p_machine)
    {{:ok, :{StateAtom(machine.StartState.Name)}, %__MODULE__{{}}, [{{:next_event, :internal, :__entry__}}]}}
  end

  @impl true
");

            foreach (var state in machine.States)
            {
                EmitState(sb, state);
            }

            sb.Append(
@"  # Catch-all: an event with no handler in the current state is dropped. Proper defer/ignore
  # handling arrives in M4.
  def handle_event(_type, _content, _state, _data), do: :keep_state_and_data
end
");

            var file = new CompiledFile(Path.Combine("lib", appName, $"{SnakeCase(machine.Name)}.ex"));
            file.Stream.Write(sb.ToString());
            return file;
        }

        private static void EmitState(StringBuilder sb, State state)
        {
            var atom = StateAtom(state.Name);

            sb.Append($"\n  # ---- state {state.Name} ----\n");

            // state_enter callback.
            sb.Append($"  def handle_event(:enter, _old_state, :{atom}, _data) do\n");
            sb.Append($"    PRuntime.entered(@p_machine, :{atom})\n");
            sb.Append("    :keep_state_and_data\n");
            sb.Append("  end\n\n");

            // entry handler, encoded as the :__entry__ internal event.
            if (state.Entry != null)
            {
                sb.Append($"  def handle_event(:internal, :__entry__, :{atom}, data) do\n");
                sb.Append(BuildHandlerBody(state, state.Entry, "    "));
                sb.Append("  end\n\n");
            }
            else
            {
                sb.Append($"  def handle_event(:internal, :__entry__, :{atom}, _data), do: :keep_state_and_data\n\n");
            }

            // on E ... handlers.
            foreach (var handler in state.AllEventHandlers)
            {
                var ev = handler.Key;
                switch (handler.Value)
                {
                    case EventDoAction doAction:
                        sb.Append($"  def handle_event(:cast, {{:p_event, :{EventAtom(ev.Name)}, _payload}}, :{atom}, data) do\n");
                        sb.Append($"    PRuntime.dequeued(@p_machine, :{atom}, :{EventAtom(ev.Name)})\n");
                        sb.Append(BuildHandlerBody(state, doAction.Target, "    "));
                        sb.Append("  end\n\n");
                        break;

                    case EventGotoState gotoState:
                        sb.Append($"  def handle_event(:cast, {{:p_event, :{EventAtom(ev.Name)}, _payload}}, :{atom}, data) do\n");
                        sb.Append($"    PRuntime.dequeued(@p_machine, :{atom}, :{EventAtom(ev.Name)})\n");
                        sb.Append($"    PRuntime.goto(@p_machine, :{atom}, :{StateAtom(gotoState.Target.Name)}, data)\n");
                        sb.Append("  end\n\n");
                        break;

                    case EventDefer _:
                    case EventIgnore _:
                        sb.Append($"  # TODO(M4): {handler.Value.GetType().Name} for {ev.Name}\n");
                        sb.Append($"  def handle_event(:cast, {{:p_event, :{EventAtom(ev.Name)}, _payload}}, :{atom}, _data), do: :keep_state_and_data\n\n");
                        break;
                }
            }
        }

        /// <summary>
        /// Emits the body of an entry/handler function as the tail of a <c>handle_event</c> clause.
        /// M1 supports <c>goto</c> and <c>raise halt</c> (both terminal, producing the gen_statem
        /// return). Anything else is emitted as a TODO comment; if no terminal statement is present
        /// the clause falls through to <c>:keep_state_and_data</c>.
        ///
        /// The front-end lowers expressions through temporaries, so <c>raise halt</c> arrives as
        /// <c>tmp = halt; raise tmp;</c>. We track temporaries assigned an event reference so a
        /// later <c>raise tmp</c> can be resolved back to its event (and recognised as halt).
        /// </summary>
        private static string BuildHandlerBody(State state, Function fn, string indent)
        {
            var sb = new StringBuilder();
            var terminal = false;
            var eventVars = new Dictionary<Variable, Event>();

            if (fn?.Body != null)
            {
                foreach (var stmt in fn.Body.Statements)
                {
                    switch (stmt)
                    {
                        // tmp = <event>: remember the binding, emit nothing. The value is wrapped
                        // in a CloneExpr (deep copy) by the front-end, hence the unwrap.
                        case AssignStmt assign
                            when assign.Location is VariableAccessExpr target && Unwrap(assign.Value) is EventRefExpr eventRef:
                            eventVars[target.Variable] = eventRef.Value;
                            break;

                        case GotoStmt gotoStmt:
                            sb.Append($"{indent}PRuntime.goto(@p_machine, :{StateAtom(state.Name)}, :{StateAtom(gotoStmt.State.Name)}, data)\n");
                            terminal = true;
                            break;

                        case RaiseStmt raiseStmt when ResolveEvent(raiseStmt.Event, eventVars) is { IsHaltEvent: true }:
                            sb.Append($"{indent}PRuntime.halt(@p_machine, :{StateAtom(state.Name)}, data)\n");
                            terminal = true;
                            break;

                        default:
                            sb.Append($"{indent}# TODO(M2+): unsupported statement {stmt.GetType().Name}\n");
                            break;
                    }
                }
            }

            if (!terminal)
            {
                sb.Append($"{indent}:keep_state_and_data\n");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Resolves an event-typed expression to its <see cref="Event"/>: either a direct event
        /// reference, or a temporary previously assigned one. Returns null if it cannot be resolved
        /// statically (e.g. a computed event), which M1 does not yet support.
        /// </summary>
        private static Event ResolveEvent(IPExpr expr, IReadOnlyDictionary<Variable, Event> eventVars)
        {
            return Unwrap(expr) switch
            {
                EventRefExpr eventRef => eventRef.Value,
                VariableAccessExpr varAccess when eventVars.TryGetValue(varAccess.Variable, out var ev) => ev,
                _ => null
            };
        }

        // The front-end wraps copied values in a CloneExpr; strip it to inspect the underlying term.
        private static IPExpr Unwrap(IPExpr expr) => expr is CloneExpr clone ? clone.Term : expr;

        // P state/event names are PascalCase identifiers; quoting keeps the emitted atom valid for
        // any name (e.g. names that aren't lowercase) without special-casing.
        private static string StateAtom(string name) => $"\"{name}\"";

        private static string EventAtom(string name) => $"\"{name}\"";

        /// <summary>
        /// Derives an Elixir module alias (PascalCase, e.g. <c>ClientServer</c>) from the P project
        /// name. A configurable <c>--module-prefix</c> option is planned but not part of this scaffold.
        /// </summary>
        private static string ModulePrefix(ICompilerConfiguration job)
        {
            var segments = SplitIdentifier(job.ProjectName);
            if (segments.Count == 0)
            {
                return "PGenerated";
            }

            var sb = new StringBuilder();
            foreach (var segment in segments)
            {
                sb.Append(char.ToUpperInvariant(segment[0]));
                if (segment.Length > 1)
                {
                    sb.Append(segment.Substring(1));
                }
            }

            // Elixir module aliases (and the derived snake_case atom) must start with a letter.
            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, 'P');
            }
            return sb.ToString();
        }

        /// <summary>
        /// Converts a PascalCase module alias to a snake_case atom/path segment usable as a mix
        /// app name and the <c>lib/&lt;app&gt;/</c> directory (e.g. <c>ClientServer</c> → <c>client_server</c>).
        /// </summary>
        private static string SnakeCase(string modulePrefix)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < modulePrefix.Length; i++)
            {
                var c = modulePrefix[i];
                if (char.IsUpper(c) && i > 0)
                {
                    sb.Append('_');
                }
                sb.Append(char.ToLowerInvariant(c));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Splits a project name into alphanumeric segments, dropping characters that are not valid
        /// in an Elixir identifier (so names like <c>2PhaseCommit</c> or <c>my-proj</c> still yield a
        /// usable module alias).
        /// </summary>
        private static List<string> SplitIdentifier(string name)
        {
            var segments = new List<string>();
            if (string.IsNullOrEmpty(name))
            {
                return segments;
            }

            var current = new StringBuilder();
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    current.Append(c);
                }
                else if (current.Length > 0)
                {
                    segments.Add(current.ToString());
                    current.Clear();
                }
            }
            if (current.Length > 0)
            {
                segments.Add(current.ToString());
            }

            // Elixir module aliases must start with a letter; drop leading all-digit segments.
            return segments.SkipWhile(s => s.All(char.IsDigit)).ToList();
        }
    }
}
