using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Plang.Compiler.TypeChecker;

namespace Plang.Compiler.Backend.Elixir
{
    /// <summary>
    /// Runtime code-generation backend that emits an executable Elixir (BEAM) mix project
    /// from a verified P program. Peer of the PChecker (C#) and PEx (Java) backends; concerned
    /// only with <em>running</em> a P design, not verifying it.
    ///
    /// This is the M1 scaffold: it emits a fixed <c>mix.exs</c> and an empty
    /// <c>&lt;Prefix&gt;.Supervisor</c> so the codegen plumbing and project shape are in place.
    /// Machine, state, event and type translation arrive in later milestones.
    ///
    /// Like PObserve, this backend has no compilation stage: the generated mix project is meant
    /// to be consumed as a dependency by a host application, which builds it with the standard
    /// Elixir toolchain (<c>mix</c>). <see cref="ICodeGenerator.HasCompilationStage"/> stays false.
    /// </summary>
    public class ElixirCodeGenerator : ICodeGenerator
    {
        public IEnumerable<CompiledFile> GenerateCode(ICompilerConfiguration job, Scope globalScope)
        {
            var modulePrefix = ModulePrefix(job);
            var appName = SnakeCase(modulePrefix);

            // WriteFile (DefaultCompilerOutput) does not create intermediate directories, and the
            // supervisor lives under lib/<app>/. Create that directory now, before the orchestrator
            // writes the returned files. PObserve follows the same "touch the output dir during
            // GenerateCode" pattern for its pom.xml.
            Directory.CreateDirectory(Path.Combine(job.OutputDirectory.FullName, "lib", appName));

            return new[]
            {
                GenerateMixExs(modulePrefix, appName),
                GenerateSupervisor(modulePrefix, appName)
            };
        }

        private static CompiledFile GenerateMixExs(string modulePrefix, string appName)
        {
            var file = new CompiledFile("mix.exs");
            file.Stream.Write(
$@"defmodule {modulePrefix}.MixProject do
  use Mix.Project

  def project do
    [
      app: :{appName},
      version: ""0.1.0"",
      elixir: ""~> 1.17"",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # No `mod:` application callback by default: starting machines on Application.start is
  # surprising. The host adds {modulePrefix}.Supervisor to its own supervision tree explicitly.
  def application do
    [extra_applications: [:logger]]
  end

  defp deps do
    [
      # {{:p_runtime, ""~> 0.1""}}
    ]
  end
end
");
            return file;
        }

        private static CompiledFile GenerateSupervisor(string modulePrefix, string appName)
        {
            var file = new CompiledFile(Path.Combine("lib", appName, "supervisor.ex"));
            file.Stream.Write(
$@"defmodule {modulePrefix}.Supervisor do
  @moduledoc """"""
  Entry point for the generated P program. The host adds this module to its own
  supervision tree; it owns the supervision of P machines (and, later, the registry
  and any static spec processes).

  Generated by the P compiler's Elixir backend. This is the M1 scaffold and does not
  yet start any machines.
  """"""
  use Supervisor

  def start_link(init_arg \\ []) do
    Supervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
    children = []
    Supervisor.init(children, strategy: :one_for_one)
  end
end
");
            return file;
        }

        /// <summary>
        /// Derives an Elixir module alias (PascalCase, e.g. <c>ClientServer</c>) from the P project
        /// name. A configurable <c>--module-prefix</c> option is planned but not part of this scaffold.
        /// </summary>
        private static string ModulePrefix(ICompilerConfiguration job)
        {
            var segments = SplitIdentifier(job.ProjectName);
            if (segments.Count == 0)
            {
                return "PGenerated";
            }

            var sb = new StringBuilder();
            foreach (var segment in segments)
            {
                sb.Append(char.ToUpperInvariant(segment[0]));
                if (segment.Length > 1)
                {
                    sb.Append(segment.Substring(1));
                }
            }

            // Elixir module aliases (and the derived snake_case atom) must start with a letter.
            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, 'P');
            }
            return sb.ToString();
        }

        /// <summary>
        /// Converts a PascalCase module alias to a snake_case atom/path segment usable as a mix
        /// app name and the <c>lib/&lt;app&gt;/</c> directory (e.g. <c>ClientServer</c> → <c>client_server</c>).
        /// </summary>
        private static string SnakeCase(string modulePrefix)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < modulePrefix.Length; i++)
            {
                var c = modulePrefix[i];
                if (char.IsUpper(c) && i > 0)
                {
                    sb.Append('_');
                }
                sb.Append(char.ToLowerInvariant(c));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Splits a project name into alphanumeric segments, dropping characters that are not valid
        /// in an Elixir identifier (so names like <c>2PhaseCommit</c> or <c>my-proj</c> still yield a
        /// usable module alias).
        /// </summary>
        private static List<string> SplitIdentifier(string name)
        {
            var segments = new List<string>();
            if (string.IsNullOrEmpty(name))
            {
                return segments;
            }

            var current = new StringBuilder();
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    current.Append(c);
                }
                else if (current.Length > 0)
                {
                    segments.Add(current.ToString());
                    current.Clear();
                }
            }
            if (current.Length > 0)
            {
                segments.Add(current.ToString());
            }

            // Elixir module aliases must start with a letter; drop leading all-digit segments.
            return segments.SkipWhile(s => s.All(char.IsDigit)).ToList();
        }
    }
}
